<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260921092236 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE folder (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, ref VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE all_password ADD folder_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE all_password ADD CONSTRAINT FK_A43C1112162CB942 FOREIGN KEY (folder_id) REFERENCES folder (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_A43C1112162CB942 ON all_password (folder_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE folder');
        $this->addSql('ALTER TABLE all_password DROP CONSTRAINT FK_A43C1112162CB942');
        $this->addSql('DROP INDEX IDX_A43C1112162CB942');
        $this->addSql('ALTER TABLE all_password DROP folder_id');
    }
}
