<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260918112137 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE all_password (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, identifier VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, site VARCHAR(255) NOT NULL, nonce VARCHAR(255) NOT NULL, tag VARCHAR(255) NOT NULL, uuid UUID NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A43C1112D17F50A6 ON all_password (uuid)');
        $this->addSql('CREATE INDEX IDX_A43C1112A76ED395 ON all_password (user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, master_key_hash VARCHAR(255) DEFAULT NULL, master_salt VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('ALTER TABLE all_password ADD CONSTRAINT FK_A43C1112A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE all_password DROP CONSTRAINT FK_A43C1112A76ED395');
        $this->addSql('DROP TABLE all_password');
        $this->addSql('DROP TABLE "user"');
    }
}
